MACOSX_SDK_VERSION:        # [osx]
  - '12.3'                 # [osx]
c_compiler:                # [win]
  - clang                  # [win]
cxx_compiler:              # [win]
  - clang                  # [win]
c_compiler_version:        # [win]
  - 17.0.6                 # [win]
cxx_compiler_version:      # [win]
  - 17.0.6                 # [win]